sudo: false
language: ruby
rvm:
  - 2.6.4
  - 2.5.6
  - 2.4.7

before_install:
  - gem install bundler -v '~> 1.17'

gemfile:
  - gemfiles/rails_5.0.x.gemfile
  - gemfiles/rails_5.1.x.gemfile
  - gemfiles/rails_5.2.x.gemfile
  - gemfiles/rails_6.0.x.gemfile

matrix:
  exclude:
    - rvm: 2.4.7
      gemfile: gemfiles/rails_6.0.x.gemfile
